### ISSUE TITLE
请求支持macos13

### ISSUE THREAD

**Issue by terwer** [cnblogs/cli#2]
![image](https://github.com/cnblogs/cli/assets/3259282/8133a963-d9b5-4033-89c1-90a54f196360)
目前 最新版macos12 在macos13上不能运行

**Comment by Thaumy** [comment]
您好，会在下个版本尝试提供 macOS 13 支持。

**Comment by Thaumy** [comment]
0.1.4 已发布：[https://github.com/cnblogs/cli/releases/tag/v0.1.4](https://github.com/cnblogs/cli/releases/tag/v0.1.4)
提供了 macOS 13 的构建产物，您可以尝试运行。

**Comment by terwer** [comment]
可以了，太棒了，支持博客园👍🏻
